In [1]:
import numpy as np
import pandas as pd

In [4]:
!git clone https://github.com/anvarnarz/praktikum_datasets.git

Cloning into 'praktikum_datasets'...

# Тарзҳои хондани  csv - файл

In [14]:
df = pd.read_csv('praktikum_datasets/merc.csv') # Кушодани csv - файл
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [16]:
df = pd.read_csv('praktikum_datasets/merc.csv', index_col = 0) # Кушодани csv - файл ва ба ҷои индексаш номи model - ро додан
df.head()

          year  price transmission  mileage fuelType  tax   mpg  engineSize
model
SLK       2005   5200    Automatic    63000   Petrol  325  32.1         1.8
S Class   2017  34948    Automatic    27000   Hybrid   20  61.4         2.1
SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0         5.5
G Class   2016  61948    Automatic    16000   Petrol  325  30.4         4.0
G Class   2016  73948    Automatic     4000   Petrol  325  30.1         4.0

In [18]:
df1 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/automobile_data.csv', index_col = 'index', nrows = 10) 
# Кушодани csv - файл аз GitHub link - ро гирифта ба индексаш худи индекси дар дохили файл бударо гузошта
# nrows - барои якбора ҷудо кардани каторҳо агар ба мо дидани ҳамаи қаторҳо лозим набошад                
df1

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970

# Тарзи сохранит кардан дар csv - файл

In [23]:
df.to_csv('new_merc.csv')

# Тарзҳои хондани excel - файл

In [20]:
df2 = pd.read_excel('praktikum_datasets/netflix.xlsx') # Кушодани excel - файл
df2

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [21]:
df2 = pd.read_excel('praktikum_datasets/netflix.xlsx', index_col = 0) 
# Кушодани excel - файл ва ба индексаш қиймати title - ро додан
df2

,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
title,,,,,,
White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...
The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
Growing Up Wild,G,NaN,35,2016,80.0,80

In [24]:
df2 = pd.read_excel('praktikum_datasets/netflix.xlsx', index_col = 0, nrows = 15)
# Кушодани excel - файл ва ба индексаш қиймати title - ро додан
# nrows - барои якбора ҷудо кардани каторҳо агар ба мо дидани ҳамаи қаторҳо лозим набошад
df2

,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
title,,,,,,
White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
Naruto,TV-PG,Parental guidance suggested. May not be suitab...,70,2008,88.0,80
The Hunter,R,language and brief violence,100,2011,NaN,82

# Тарзҳои сохранит кардан дар excel - файл

In [25]:
df2.to_excel('netflix.xlsx')

In [26]:
df2.to_excel('netflix.xlsx', index = False)

# HDF5

In [33]:
hdfobj = pd.HDFStore('data.h5') # Шакли сохтани hdf5

In [34]:
hdfobj.put('cardata', df) # Дар дохили hdf5 дигар файлро дохил кардан

In [35]:
hdfobj.keys() # Калидҳои hdf - ро дидан

['/cardata', '/data']

In [36]:
hdfobj['cardata']

           year  price transmission  mileage fuelType  tax   mpg  engineSize
model
SLK        2005   5200    Automatic    63000   Petrol  325  32.1         1.8
S Class    2017  34948    Automatic    27000   Hybrid   20  61.4         2.1
SL CLASS   2016  49948    Automatic     6200   Petrol  555  28.0         5.5
G Class    2016  61948    Automatic    16000   Petrol  325  30.4         4.0
G Class    2016  73948    Automatic     4000   Petrol  325  30.1         4.0
...         ...    ...          ...      ...      ...  ...   ...         ...
C Class    2020  35999    Automatic      500   Diesel  145  55.4         2.0
B Class    2020  24699    Automatic     2500   Diesel  145  55.4         2.0
GLC Class  2019  30999    Automatic    11612   Diesel  145  41.5         2.1
CLS Class  2019  37990    Automatic     2426   Diesel  145  45.6         2.0
S Class    2019  54999    Automatic     2075   Diesel  145  52.3         2.9

[13119 rows x 8 columns]

In [43]:
hdfobj.close # Баъд аз анҷоми кор файлро маҳкам кардан

<bound method HDFStore.close of <class 'pandas.io.pytables.HDFStore'>
File path: data.h5
>

In [45]:
#data = pd.read_hdf('data.h5', key = 'cardata')
# Тарзи хондани hdf - файл

In [47]:
#data.to_hdf('data.h5')
# Тарзи сохранит кардани hdf - файл

# Хондани Web - файлҳо яъне аз интернет

In [49]:
dushanbe = pd.read_html('https://en.wikipedia.org/wiki/Dushanbe') 
# Хондани файлҳои аз интернет link - ро гирифта мегузоред

In [53]:
len(dushanbe) # Дар дохили саҳифаи Dushanbe чандто ҷадвал буданашро дидан

22

In [54]:
dushanbe[0] # 1 - ум ҷадвалро дидан

,Dushanbe Душанбe,Dushanbe Душанбe.1
0,Capital city,Capital city
1,Clockwise from top: Palace of the Nation and D...,Clockwise from top: Palace of the Nation and D...
2,Seal,Seal
3,Location of Dushanbe in Tajikistan,Location of Dushanbe in Tajikistan
4,DushanbeDushanbeDushanbe,DushanbeDushanbeDushanbe
5,Coordinates: 38°32′12″N 68°46′48″E﻿ / ﻿38.5366...,Coordinates: 38°32′12″N 68°46′48″E﻿ / ﻿38.5366...
6,Country,Tajikistan
7,Region,Dushanbe
8,Named for,Monday
9,Districts,List Ismail SamaniAvicennaFerdowsiShah Mansur
10,Government,Government
11,• Shahrdar (Mayor),Rustam Emomali (PDPT)
12,Area[2],Area[2]
13,• Land,203 km2 (78 sq mi)
14,• Urban,185 km2 (71 sq mi)
15,Elevation[3][4][5],"823 m (2,700 ft)"
16,Highest elevation,"930 m (3,050 ft)"
17,Lowest elevation,"750 m (2,460 ft)"
18,Population (March 2024),Population (March 2024)
19,• Capital city,"1,564,700[1]"
20,• Rank,1st in Tajikistan
21,• Metro,"3,147,000[1]"
22,Time zone,UTC+5 (GMT+5)
23,• Summer (DST),UTC+5 (Tajikistan Time)
24,Postal code,6-Digit
25,Area code,372[3]
26,Vehicle registration,"01, 05[6]"
27,HDI (2021),0.756[7] high
28,Official languages,Russian (Interethnic) Tajik (State)[8]
29,Website,www.dushanbe.tj

In [55]:
dushanbe[1] # 2 -ум ҷадвали дар саҳифаи Душанбе бударо дидан

   Climate data for Dushanbe (1991–2020, extremes 1926–present)  \
                                                          Month
0                                 Record high °C (°F)
1                          Mean daily maximum °C (°F)
2                                  Daily mean °C (°F)
3                          Mean daily minimum °C (°F)
4                                  Record low °C (°F)
5                   Average precipitation mm (inches)
6               Average precipitation days (≥ 1.0 mm)
7                       Average relative humidity (%)
8                         Mean monthly sunshine hours
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Jan
0                                         21.8 (71.2)
1                                          9.0 (48.2)
2                                          3.1 (37.6)
3                                         −0.9 (30.4)
4                                       −26.6 (−15.9)
5                                           100 (3.9)
6                                                 8.5
7                                                  69
8                                                 120
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Feb
0                                         27.7 (81.9)
1                                         11.0 (51.8)
2                                          5.0 (41.0)
3                                          0.5 (32.9)
4                                         −17.6 (0.3)
5                                            95 (3.7)
6                                                 9.1
7                                                  67
8                                                 121
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Mar
0                                         32.2 (90.0)
1                                         17.0 (62.6)
2                                         10.5 (50.9)
3                                          5.5 (41.9)
4                                         −12.9 (8.8)
5                                           102 (4.0)
6                                                13.4
7                                                  65
8                                                 156
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Apr
0                                         36.2 (97.2)
1                                         22.8 (73.0)
2                                         15.8 (60.4)
3                                         10.1 (50.2)
4                                         −6.1 (21.0)
5                                           112 (4.4)
6                                                 9.8
7                                                  63
8                                                 198
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  May
0                                        38.8 (101.8)
1                                         27.9 (82.2)
2                                         20.1 (68.2)
3                                         13.4 (56.1)
4                                          1.2 (34.2)
5                                            75 (3.0)
6                                                 7.8
7                                                  57
8                                                 281
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Jun
0                                        44.1 (111.4)
1                                         33.6 (92.5)
2                                         25.1 (77.2)
3                                         17.2 (63.0)
4                                          8.4 (47.1)
5                                            17 (0.7)
6                                                 1.5
7                                                  42
8                                                 337
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Jul
0                                        43.7 (110.7)
1                                         36.4 (97.5)
2                                         27.4 (81.3)
3                                         18.9 (66.0)
4                                         10.9 (51.6)
5                                             4 (0.2)
6                                                 0.7
7                                                  41
8                                                 352
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Aug
0                                        45.0 (113.0)
1                                         35.5 (95.9)
2                                         26.0 (78.8)
3                                         17.2 (63.0)
4                                          8.2 (46.8)
5                                             1 (0.0)
6                                                 0.1
7                                                  44
8                                                 338
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Sep
0                                        38.9 (102.0)
1                                         31.3 (88.3)
2                                         21.2 (70.2)
3                                         12.7 (54.9)
4                                         −1.0 (30.2)
5                                             4 (0.2)
6                                                 0.8
7                                                  44
8                                                 289
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Oct
0                                         36.8 (98.2)
1                                         24.4 (75.9)
2                                         14.7 (58.5)
3                                          7.8 (46.0)
4                                         −4.4 (24.1)
5                                            29 (1.1)
6                                                 3.7
7                                                  56
8                                                 224
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Nov
0                                         31.9 (89.4)
1                                         16.7 (62.1)
2                                          9.0 (48.2)
3                                          3.8 (38.8)
4                                         −13.5 (7.7)
5                                            55 (2.2)
6                                                 5.3
7                                                  63
8                                                 164
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

                                                       \
                                                  Dec
0                                         24.3 (75.7)
1                                         11.1 (52.0)
2                                          4.6 (40.3)
3                                          0.4 (32.7)
4                                        −19.5 (−3.1)
5                                            60 (2.4)
6                                                 8.1
7                                                  69
8                                                 119
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...


                                                 Year
0                                        45.0 (113.0)
1                                         23.1 (73.6)
2                                         15.2 (59.4)
3                                          8.9 (48.0)
4                                       −26.6 (−15.9)
5                                          654 (25.7)
6                                                68.8
7                                                  57
8                                                2699
9                         Source 1: Pogoda.ru.net[98]
10  Source 2: Deutscher Wetterdienst (humidity 195...

# JSON ва аз API хондан

Барои хондани JSON файлҳо ба мо аввал китобхонаи requests лозим аст. Ва баъд link - ро гирифта истифода бурда метавонем

In [56]:
import requests
r = requests.get('http://openlibrary.org/subjects/python.json?published_in=2010-2024')

In [57]:
r.status_code # Агар ба ҷои 200 дигар ададҳо масалан 404 барояд ин хато кор карда истодааст

200

In [60]:
json_df = pd.DataFrame(r.json()['works']) # Тарзи хондани JSON - файл
json_df.head()

,key,title,edition_count,cover_id,cover_edition_key,subject,ia_collection,lendinglibrary,printdisabled,lending_edition,lending_identifier,authors,first_publish_year,ia,public_scan,has_fulltext,availability
0,/works/OL2784125W,Learning Python,20,1312568.0,OL9497269M,"[Python (Langage de programmation), Python (li...","[americana, inlibrary, internetarchivebooks, p...",False,True,OL37873566M,einfuhrunginpyth0000lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1999,einfuhrunginpyth0000lutz,False,True,"{'status': 'borrow_available', 'available_to_b..."
1,/works/OL2784127W,Python,13,988215.0,OL8942751M,"[Python (Computer program language), Python (L...","[americana, binghamton-ol, inlibrary, internet...",False,True,OL7581213M,pythonpocketrefe00lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1998,pythonpocketrefe00lutz,False,True,"{'status': 'borrow_available', 'available_to_b..."
2,/works/OL16976951W,Think Python,11,7363360.0,OL25763659M,"[Computer programming, Software architecture, ...","[additional_collections, folkscanomy, folkscan...",False,True,OL26455778M,2015ThinkPython,"[{'key': '/authors/OL6815485A', 'name': 'Allen...",2009,2015ThinkPython,True,True,"{'status': 'open', 'available_to_browse': Fals..."
3,/works/OL2784126W,Programming Python,10,805644.0,OL8667192M,"[Python (Computer program language), Python (c...","[americanuniversity-ol, inlibrary, internetarc...",False,True,OL3969544M,programmingpytho00lutz,"[{'key': '/authors/OL411267A', 'name': 'Mark L...",1996,programmingpytho00lutz,False,True,"{'status': 'borrow_available', 'available_to_b..."
4,/works/OL17795703W,Python for bioinformatics,10,8078288.0,OL26385029M,"[Bioinformatics, Python (computer program lang...",[],False,False,,,"[{'key': '/authors/OL3871440A', 'name': 'Sebas...",2009,None,False,False,NaN

# Тарзи сохранит кардани JSON файл

In [61]:
json_df.to_json('openlibrary_python.json')

# Агар дар вақти хондани html - файл хатоги диҳад бояд дар Windows PowerShell - pip install lxml установка кардан лозим аст

Дар вақти хатоги додан дар хондани HDF5 дар PowerShell - pip install tables установка кардан лозим аст.

- Манба: praktikum mohirdev